title: Cory Pruce # Pruce Systems #  
description: # > # this means to ignore newlines until "baseurl:"
  Data Science/Machine Learning/Software Engineering 
show_downloads: true

#theme: jekyll-theme-cayman-blog

baseurl: "" #"/pruce-data-systems-blog" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://cpruce.github.io" # change this to the base hostname & protocol for your site

google_analytics:
# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cpruce-blog: #cayman-blog:
  date_format: "%b %-d, %Y"

theme: # leave it empty
redirects: yes
# social
author: "Cory Pruce"
image: /img/cover.png 
github:
  username: Cpruce
  owner_name: Cory
twitter:
  username: cory_pruce 
#  site:
facebook:
  #publisher: 1592372034171500
  #profile_id: 1809805629
  #app_id: 1798910940422432 
#  admins
